### ISSUE TITLE
Need to Support Client SAMP - R5 Soon....

### ISSUE THREAD

**Issue by AtlanticCityRoleplay** [CyberMor/sampvoice#112]

**Comment by HenriKenn** [comment]
+1

**Comment by soypeto** [comment]
+2

**Comment by Adib23704** [comment]
https://github.com/CyberMor/sampvoice/issues/113

Not planned by @CyberMor

**Comment by AtlanticCityRoleplay** [comment]
> https://github.com/CyberMor/sampvoice/issues/113
> 
> Not planned by @CyberMor 

Thanks for the Response ☹️
