### ISSUE TITLE
Translate to other Language

### ISSUE THREAD

**Issue by AndreeFreitas** [CyberMor/sampvoice#114]
It's possible change language ? How i do this ?

**Comment by CyberMor** [comment]
In the new version of the plugin, I will try to put all the localizable data into a separate file. It can be translated into other languages. For now, you can find the lines here https://github.com/CyberMor/sampvoice/blob/be4f8afe6a4141c5b533b91c2662d39fd332f6ab/client/PluginMenu.h#L73
