### ISSUE TITLE
Multiple channel

### ISSUE THREAD

**Issue by zizzgamer** [CyberMor/sampvoice#60]
is there any idea to create multiple voice channel for global voice chat. I made global channel as a mobile system with network busy system. I would like to add multiple global voice channel for radio additionally. If I create additional variable rather than 1 local and 1 global it crashes..

**Comment by zizzgamer** [comment]
Done myself... Thanks..

**Comment by AsherSmithh** [comment]
Can you tell me how to create multiple voice channel? thanks
