### ISSUE TITLE
 Failed (libbass.so: cannot open shared object file: No such file or directory)

### ISSUE THREAD

**Issue by Emialcaraz** [CyberMor/sampvoice#7]
Hello, I'm trying to add this to my server, but I have a problem:

 Failed (libbass.so: cannot open shared object file: No such file or directory)

I have added libbass.so to /usr/local/lib/ /usr/lib/ usr/lib64/
but don't have success with it.

I'm using centos6

**Comment by Emialcaraz** [comment]
whereis libbass
libbass: /usr/bin/libbass.so /lib/libbass.so /usr/lib/libbass.so /usr/lib64/libbass.so /usr/local/lib/libbass.so

but the error is the same.

**Comment by Emialcaraz** [comment]
Fixed thw issue creating a folder in /home/mor/sampvoice and adding libbass.so in there.

Now I have another issue but I will close this here.

**Comment by MaximBzg** [comment]
@Emialcaraz Were you able to make this work? In my case it never calls the OnPlayerVoice callback.
