### ISSUE TITLE
Undefined SvCreateEffectEcho

### ISSUE THREAD

**Issue by devG-afk** [CyberMor/sampvoice#77]
CMD:mv(playerid, params[])
{
	new SV_EFFECT:mphone[MAX_PLAYERS] = { SV_NULL, ... };
	new SV_LSTREAM:cphone = SV_NULL;
	if((mphone[playerid] = SvCreateEffectEcho("mphone",60,0 ,10.0, 10.0, 10.0, 10.0, 10.0)))
	{
		SendClientMessage(playerid, -1, "Activated");

		if(cphone) SvEffectAttachStream(cphone, playerid);
		SvAddKey(playerid, 0x42);
	}
	return 1;
}

D:\Horizon Roleplay\gamemodes\HRP_9.0.pwn(33172) : error 017: undefined symbol "SvCreateEffectEcho"
Pawn compiler 3.2.3664	 	 	Copyright (c) 1997-2016, ITB CompuPhase

**Comment by ParadoxRP** [comment]
Wouldn't it be because SvCreateEffectEcho is wrong? "SvEffectCreateEcho"

**Comment by devG-afk** [comment]
oh i see thank you very much
